AWSTemplateFormatVersion: "2010-09-09"
Description: ECR resource template. it is an original template of Msksgm
Resources:
  EcrBackendRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Delete
    Properties:
      RepositoryName: sbcntr-backend-app
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256
  EcrFrontendRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Delete
    Properties:
      RepositoryName: sbcntr-frontend-app
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256
